apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.fullname }} 
spec:
  replicas: {{.Values.replicas.default}}
  selector:
    matchLabels:
      app: {{.Values.name }} 
  template:
    metadata:
      labels:
        app: {{.Values.name }} 
    spec:
      imagePullSecrets:
      - name : jfrogsecret
      containers:
      - name: {{.Values.name }} 
        image: "{{.Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        command: ["/entrypoint.sh"]
        args: ["dev"]
        env: 
        - name: ENVIRONMENT
          value: {{.Values.env }} 