apiVersion: v1
kind: Service
metadata:
  name: {{.Values.fullname }}
spec:
  selector:
    app:  {{.Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.targetPort}}
      nodePort: {{.Values.nodeport}}
  type: NodePort